### ISSUE TITLE
EntityOrchestrator

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa-nlu-examples#136]
Let's say that we have a RegexEE and DIET in our pipeline. For the RegexEE to work we need to have a few labels with entities in our nlu data. This will also prompt DIET to pick those training examples which might lead to conflicts later.

We could add a component in our pipeline, say a `EntityOrchestrator` that can pick up entity predictions in the NLU message like; 

```json
{   "text": "hello vincent",
    "entities": [
        {
            "entity": "name",
            "start": 6,
            "end": 13,
            "confidence_entity": 1, 
            "value": "vincent",
            "extractor": "DIETEntityExtractor"
        },{
            "entity": "name",
            "start": 6,
            "end": 13,
            "confidence_entity": 1, 
            "value": "vincent",
            "extractor": "RegexEntityExtractor"
        }
    ]
}
```

and can turn it into either. 

<details>
  <summary><b>Option 1: The entityextractor of choice.</b></summary>

The idea would be that you can configure a hierarchy/priority within entity extractors. 

```json
{   "text": "hello vincent",
    "entities": [{
            "entity": "name",
            "start": 6,
            "end": 13,
            "confidence_entity": 1, 
            "value": "vincent",
            "extractor": "RegexEntityExtractor"
        }
    ]
}
```

To get this to work you'd like need to configure something like; 

```yml
pipeline:
    - name: EntityOrchestrator
      priority:
          name: RegexEntityExtractor #all names can only be detected by RegexEntityExtractor
          date: DucklingEntityExtractor  #all dates can only be detected by DucklingEntityExtractor
```
</details>

<details>
  <summary><b>Option 2: Override and Pick.</b></summary>

We could also just fold detected entities together.
```json
{   "text": "hello vincent",
    "entities": [
       {
            "entity": "name",
            "start": 6,
            "end": 13,
            "confidence_entity": 1, 
            "value": "vincent",
            "extractor": "EntityOrchestrator"
        }
    ]
}
```

To get this to work you'd like need to configure something like; 

```yml
pipeline:
    - name: EntityOrchestrator
      priority:
          - RegexEntityExtractor
          - DucklingEntityExtractor
          - DietClassifierEntityExtractor
```
</details>

We could also implement both options, but a component that helps in this space would be appreciated.
