### ISSUE TITLE
Warning for stopwordremover

### ISSUE THREAD

**Issue by hiiamsid** [RasaHQ/rasa-nlu-examples#154]
I was trying to remove stopword for the nlu data. And followed pipeline mentioned on the docs. But got following warning.

```
UserWarning: You have provided an invalid key `path` for component `rasa_nlu_examples.meta.StopWordRemover` in your pipeline. Valid options for `rasa_nlu_examples.meta.StopWordRemover` are:
- alias
```

And going through documentation i found that rasa_nlu_examples.meta.Printer has alias component and rasa_nlu_examples.meta.StopWordRemover has path component. Can you please check this?

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Could you share your config.yml file as well? Without it, it's fairly hard to debug. 

I would want to warn you though, this repo is currently being transitioned to Rasa 3.0.

**Comment by koaning** [comment]
I did just make an update to https://github.com/RasaHQ/rasa-nlu-examples/blob/main/rasa_nlu_examples/meta/stopwordremover.py. I just added `path` as a default.

**Comment by hiiamsid** [comment]
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: hi

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: rasa_nlu_examples.meta.StopWordRemover
    path: /content/drive/MyDrive/small_chatbot/embed/stopword.txt
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
    number_additional_patterns: 10
  - name: LexicalSyntacticFeaturizer
  - name: rasa_nlu_examples.featurizers.dense.GensimFeaturizer
    cache_dir: /content/drive/MyDrive/small_chatbot/embed
    file: small_dataset_word2vec
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 5
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3
  - name: rasa_nlu_examples.featurizers.dense.FastTextFeaturizer
    cache_dir: /content/drive/MyDrive/small_chatbot/embed
    file: small_fasttext.bin
  - name: DIETClassifier
    random_seed: 42
    epochs: 1000
    embedding_dimension: 30
    batch_size: 64
    drop_rate: 0.25
    learning_rate: 0.0001
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100
  # - name: FallbackClassifier
  #   threshold: 0.3
  #   ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
```
