### ISSUE TITLE
Error initializing graph component

### ISSUE THREAD

**Issue by BelenSantamaria** [RasaHQ/rasa-nlu-examples#163]
Hi, 
I am developing a bot with rasa and I wanted to include the component rasa_nlu_examples.extractors.FlashTextEntityExtractor.

I have added it to my configuration file which is as follows:

```
recipe: default.v1

language: es

pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: rasa_nlu_examples.extractors.FlashTextEntityExtractor
     case_sensitive: True
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.2
     ambiguity_threshold: 0.01

policies:
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
```
I have also added to my nlu file a lookup table with some countries, I add the start below as an example:

```
version: '3.0'
nlu:
  - lookup: pais
    examples: |
      - Afganistán
      - Åland
      - Albania
      - Alemania
      - Andorra
```

When using the command `rasa train`  it trains a model and saves it in the models folder but when using `rasa shell` or `rasa interactive` it gives me the following error:

ERROR    rasa.core.agent  - Could not load model due to Error initializing graph component for node 'run_rasa_nlu_examples.extractors.FlashTextEntityExtractor5'..

```
Versions:

Windows 11
rasa==3.0.4
rasa-nlu-examples @ git+https://github.com/RasaHQ/rasa-nlu-examples@c762a7ebcaef23220b20280db2546415a5b1622e
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @mvielkind will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
This feels related to https://github.com/RasaHQ/rasa-3.x-component-examples/pull/5. Will dive in.

**Comment by koaning** [comment]
This was an issue with documentation, super sorry! This was my bad. 

The docs still had the old version listed from Rasa 2.0. The new version no longer uses lookups but uses a `path` variable instead to point to a file. I just pushed a new version of [the docs](https://rasahq.github.io/rasa-nlu-examples/docs/extractors/flashtext/), could you confirm if the issues persists?

**Comment by BelenSantamaria** [comment]
Hi,
 I just tried it and it keeps giving me the same error, I include the configuration file with the changes:
```
recipe: default.v1

language: es

pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: rasa_nlu_examples.extractors.FlashTextEntityExtractor
     case_sensitive: False
     path: data/countries.txt
     entity_name: pais
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.2
     ambiguity_threshold: 0.01

policies:
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
```

I also attach my [countries.txt](https://github.com/RasaHQ/rasa-nlu-examples/files/7950240/countries.txt) file
