### ISSUE TITLE
CustomPythonComponent

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa-nlu-examples#39]
**Goal** 

To make hacking around easier for our research department, it might make sense to have a component that can just apply a function on a message.

The idea is that you as a user can define a file, say `custom_component.py` like; 

```python
# custom_component.py
from rasa_nlu_examples.meta import CustomPythonComponent
model = load_fasttext()

def fasttext(message, setting_a=1, setting_b=2):
    """this is pseudocode"""
    model.process(message) 
    return message # this message now has extra features attached

MyFastTextTool = CustomPythonComponent(fasttext, setting_a=1, setting_b=2)
```

Once such a file is around your project, it'd be cool if you could do; 

```yaml
language: en

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: rasa_nlu_examples.meta.Printer
  alias: before count vectors
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: rasa_nlu_examples.meta.Printer
  alias: after count vectors
- name: custom_component.MyFastTextTool
  setting_a: 1
  setting_b: 2
- name: DIETClassifier
  epochs: 100
```

This should make it much easier to add a featurizer. We shouldn't implement internal tools with it, but this might allow for some experimentation with actual rasa tools as opposed to jupyter notebooks.
